import type { Product, Category, Attribute, User } from '@/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'ErgoComfort Chair',
    category: 'Chairs',
    price: 299.99,
    stock: 150,
    sku: 'EC-BLK-01',
    status: 'Published',
    attributes: { Color: 'Black', Material: 'Mesh' },
    imageUrl: 'https://picsum.photos/seed/chair1/600/600',
    imageHint: 'modern chair',
    createdAt: '2023-10-26',
  },
  {
    id: 'prod_002',
    name: 'LuxeLounge Sofa',
    category: 'Sofas',
    price: 899.0,
    stock: 45,
    sku: 'LLS-GRY-03',
    status: 'Published',
    attributes: { Color: 'Grey', Material: 'Velvet', Size: '3-Seater' },
    imageUrl: 'https://picsum.photos/seed/sofa1/600/600',
    imageHint: 'comfortable sofa',
    createdAt: '2023-10-25',
  },
  {
    id: 'prod_003',
    name: 'SolidOak Desk',
    category: 'Tables',
    price: 450.5,
    stock: 75,
    sku: 'SOD-OAK-LG',
    status: 'Published',
    attributes: { Color: 'Natural Oak', Material: 'Wood', Size: 'Large' },
    imageUrl: 'https://picsum.photos/seed/desk1/600/600',
    imageHint: 'office desk',
    createdAt: '2023-10-24',
  },
  {
    id: 'prod_004',
    name: 'Minimalist Bookshelf',
    category: 'Storage',
    price: 199.99,
    stock: 110,
    sku: 'MB-WHT-01',
    status: 'Published',
    attributes: { Color: 'White', Material: 'MDF' },
    imageUrl: 'https://picsum.photos/seed/bookshelf1/600/600',
    imageHint: 'minimalist bookshelf',
    createdAt: '2023-10-22',
  },
  {
    id: 'prod_005',
    name: 'AuraGlow Floor Lamp',
    category: 'Lighting',
    price: 120.0,
    stock: 200,
    sku: 'AGL-BRS-01',
    status: 'Draft',
    attributes: { Color: 'Brass', Material: 'Metal' },
    imageUrl: 'https://picsum.photos/seed/floorlamp/600/600',
    imageHint: 'minimalist lamp',
    createdAt: '2023-10-21',
  },
  {
    id: 'prod_006',
    name: 'CozyKnit Armchair',
    category: 'Chairs',
    price: 349.0,
    stock: 60,
    sku: 'CKA-CRM-01',
    status: 'Published',
    attributes: { Color: 'Cream', Material: 'Fabric' },
    imageUrl: 'https://picsum.photos/seed/armchair1/600/600',
    imageHint: 'plush armchair',
    createdAt: '2023-10-20',
  },
  {
    id: 'prod_007',
    name: 'GeoPattern Rug',
    category: 'Rugs',
    price: 159.99,
    stock: 90,
    sku: 'GPR-BLU-MD',
    status: 'Published',
    attributes: { Color: 'Blue', Size: 'Medium' },
    imageUrl: 'https://picsum.photos/seed/rug1/600/600',
    imageHint: 'stylish rug',
    createdAt: '2023-10-19',
  },
  {
    id: 'prod_008',
    name: 'Floating Nightstand',
    category: 'Storage',
    price: 129.5,
    stock: 130,
    sku: 'FN-WAL-01',
    status: 'Published',
    attributes: { Color: 'Walnut', Material: 'Wood' },
    imageUrl: 'https://picsum.photos/seed/nightstand/600/600',
    imageHint: 'floating nightstand',
    createdAt: '2023-10-18',
  },
  {
    id: 'prod_009',
    name: 'Marble Top Coffee Table',
    category: 'Tables',
    price: 399.0,
    stock: 55,
    sku: 'MCT-WHT-GLD',
    status: 'Published',
    attributes: { Color: 'White', Material: 'Marble', Size: 'Medium' },
    imageUrl: 'https://picsum.photos/seed/coffeetable/600/600',
    imageHint: 'modern coffeetable',
    createdAt: '2023-09-30',
  },
  {
    id: 'prod_010',
    name: 'Industrial Stool',
    category: 'Chairs',
    price: 79.99,
    stock: 250,
    sku: 'IS-MTL-01',
    status: 'Published',
    attributes: { Color: 'Gunmetal', Material: 'Metal' },
    imageUrl: 'https://picsum.photos/seed/stool/600/600',
    imageHint: 'wooden stool',
    createdAt: '2023-09-25',
  },
];

export const categories: Category[] = [
  { id: 'cat_01', name: 'Chairs', productCount: 3 },
  { id: 'cat_02', name: 'Sofas', productCount: 1 },
  { id: 'cat_03', name: 'Tables', productCount: 2 },
  { id: 'cat_04', name: 'Storage', productCount: 2 },
  { id: 'cat_05', name: 'Lighting', productCount: 1 },
  { id: 'cat_06', name: 'Rugs', productCount: 1 },
];

export const attributes: Attribute[] = [
  { id: 'attr_01', name: 'Color', values: ['Black', 'Grey', 'Natural Oak', 'White', 'Brass', 'Cream', 'Blue', 'Walnut', 'Gunmetal'] },
  { id: 'attr_02', name: 'Material', values: ['Mesh', 'Velvet', 'Wood', 'MDF', 'Metal', 'Fabric', 'Marble'] },
  { id: 'attr_03', name: 'Size', values: ['3-Seater', 'Large', 'Medium'] },
];

export const users: User[] = [
  { id: 'user_01', name: 'Alice Johnson', email: 'alice@example.com', role: 'Admin', lastLogin: '2023-10-26T10:00:00Z' },
  { id: 'user_02', name: 'Bob Williams', email: 'bob@example.com', role: 'Editor', lastLogin: '2023-10-25T14:30:00Z' },
  { id: 'user_03', name: 'Charlie Brown', email: 'charlie@example.com', role: 'Customer', lastLogin: '2023-10-24T18:00:00Z' },
  { id: 'user_04', name: 'Diana Miller', email: 'diana@example.com', role: 'Editor', lastLogin: '2023-10-26T11:20:00Z' },
  { id: 'user_05', name: 'Ethan Davis', email: 'ethan@example.com', role: 'Customer', lastLogin: '2023-10-23T09:05:00Z' },
];
