
import type { Product, Category, Attribute, User } from '@/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Damask Elegance Wallpaper',
    productTitle: 'Damask Elegance Wallpaper',
    productCode: 'WP-DAM-01',
    productDescription: 'A classic damask pattern wallpaper for a touch of elegance.',
    category: 'Wallpapers',
    price: 59.99,
    stock: 150,
    sku: 'WP-DAM-01',
    status: 'Published',
    attributes: { Color: 'Beige', Material: 'Vinyl', Pattern: 'Damask', brand: 'Royal Walls' },
    imageUrl: 'https://picsum.photos/seed/wallpaper1/600/600',
    productImages: ['https://picsum.photos/seed/wallpaper1/600/600'],
    imageHint: 'elegant wallpaper',
    createdAt: '2023-10-26T10:00:00Z',
    db: 'retailers',
  },
  {
    id: 'prod_002',
    name: 'Modern Geometric Mural',
    productTitle: 'Modern Geometric Mural',
    productCode: 'MRL-GEO-02',
    productDescription: 'A bold geometric mural to create a stunning feature wall.',
    category: 'Wall Murals',
    stock: 45,
    sku: 'MRL-GEO-02',
    status: 'Published',
    attributes: { Color: 'Grey', Pattern: 'Geometric', brand: 'ArtDeco' },
    imageUrl: 'https://picsum.photos/seed/mural1/600/600',
    productImages: ['https://picsum.photos/seed/mural1/600/600'],
    imageHint: 'geometric mural',
    createdAt: '2023-10-25T10:00:00Z',
    db: 'retailers',
  },
  {
    id: 'prod_003',
    name: 'Faux Wood Blinds',
    productTitle: 'Faux Wood Blinds',
    productCode: 'WB-FW-03',
    productDescription: 'Durable and stylish faux wood blinds for any room.',
    category: 'Window Blinds',
    price: 89.5,
    stock: 75,
    sku: 'WB-FW-03',
    status: 'Published',
    attributes: { Color: 'White', Material: 'PVC', brand: 'ShadeMaster' },
    imageUrl: 'https://picsum.photos/seed/blinds1/600/600',
    productImages: ['https://picsum.photos/seed/blinds1/600/600'],
    imageHint: 'white blinds',
    createdAt: '2023-10-24T10:00:00Z',
    db: 'buyers',
  },
  {
    id: 'prod_004',
    name: 'Plush Shag Carpet',
    productTitle: 'Plush Shag Carpet',
    productCode: 'CPT-SHG-04',
    productDescription: 'A soft and cozy shag carpet, perfect for living rooms.',
    category: 'Carpets',
    price: 249.99,
    stock: 110,
    sku: 'CPT-SHG-04',
    status: 'Published',
    attributes: { Color: 'Cream', Texture: 'Shag', brand: 'CozyFloors' },
    imageUrl: 'https://picsum.photos/seed/carpet1/600/600',
    productImages: ['https://picsum.photos/seed/carpet1/600/600'],
    imageHint: 'plush carpet',
    createdAt: '2023-10-22T10:00:00Z',
    db: 'retailers',
  },
  {
    id: 'prod_005',
    name: 'Frosted Privacy Window Film',
    productTitle: 'Frosted Privacy Window Film',
    productCode: 'WF-PRV-05',
    productDescription: 'Easy-to-apply frosted film for privacy and style.',
    category: 'Window Films',
    stock: 200,
    sku: 'WF-PRV-05',
    status: 'Draft',
    attributes: { Texture: 'Frosted', brand: 'Frosty' },
    imageUrl: 'https://picsum.photos/seed/film1/600/600',
    productImages: ['https://picsum.photos/seed/film1/600/600'],
    imageHint: 'frosted glass',
    createdAt: '2023-10-21T10:00:00Z',
    db: 'buyers',
  },
  {
    id: 'prod_006',
    name: 'Oak Fluted Panel',
    productTitle: 'Oak Fluted Panel',
    productCode: 'FP-OAK-06',
    productDescription: 'Elegant oak fluted panels for a modern wall treatment.',
    category: 'Fluted Panels',
    price: 120.0,
    stock: 60,
    sku: 'FP-OAK-06',
    status: 'Published',
    attributes: { Color: 'Natural Oak', Material: 'Wood', brand: 'Paneluxe' },
    imageUrl: 'https://picsum.photos/seed/panel1/600/600',
    productImages: ['https://picsum.photos/seed/panel1/600/600'],
    imageHint: 'wood panel',
    createdAt: '2023-10-20T10:00:00Z',
    db: 'retailers',
  },
];

export const categories: Category[] = [
  { id: 'cat_01', name: 'Wallpapers', description: 'A wide variety of wallpapers.' },
  { id: 'cat_02', name: 'Window Blinds', description: 'Stylish and functional window blinds.' },
  { id: 'cat_03', name: 'Wall Murals', description: 'Large-scale wall murals for a statement wall.' },
  { id: 'cat_04', name: 'Carpets', description: 'Comfortable and durable carpets.' },
  { id: 'cat_05', name: 'Window Films', description: 'Privacy and decorative window films.' },
  { id: 'cat_06', name: 'Fluted Panels', description: 'Modern fluted panels for interior design.' },
];

export const attributes: Attribute[] = [
  { id: 'attr_01', name: 'Color', category: 'Wallpapers', values: ['Beige', 'Black', 'Grey', 'White', 'Cream', 'Blue', 'Natural Oak'] },
  { id: 'attr_02', name: 'Material', category: 'Window Blinds', values: ['Vinyl', 'PVC', 'Wood', 'Fabric'] },
  { id: 'attr_03', name: 'Pattern', category: 'Wallpapers', values: ['Damask', 'Floral', 'Geometric', 'Striped', 'Solid'] },
  { id: 'attr_04', name: 'Texture', category: 'Carpets', values: ['Shag', 'Low Pile', 'Frosted', 'Smooth'] },
  { id: 'attr_05', name: 'Brand', category: 'Wallpapers', values: ['Royal Walls', 'ArtDeco', 'ShadeMaster', 'CozyFloors', 'Frosty', 'Paneluxe'] },
];

export const users: User[] = [
  { id: 'user_01', name: 'Alice Johnson', email: 'alice@example.com', role: 'Admin', createdAt: '2023-10-26T10:00:00Z', lastLogin: '2023-10-26T10:00:00Z' },
  { id: 'user_02', name: 'Bob Williams', email: 'bob@example.com', role: 'Editor', createdAt: '2023-10-25T14:30:00Z', lastLogin: '2023-10-25T14:30:00Z' },
  { id: 'user_04', name: 'Diana Miller', email: 'diana@example.com', role: 'Editor', createdAt: '2023-10-26T11:20:00Z', lastLogin: '2023-10-26T11:20:00Z' },
];
